name: Update Notion from CSV

on:
  push:
    paths:
      - "scanned-items.csv"  # Trigger when this file changes
  workflow_dispatch:        # Allow manual triggering

jobs:
  retrieve-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @notionhq/client csv-parse

      - name: Retrieve Notion database schema
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node retrieve-schema.js

  update-notion:
    needs: retrieve-schema
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @notionhq/client csv-parse

      - name: Update Notion database
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node update-notion.js
